apiVersion: v1
kind: Pod
metadata:
  name: metadata-service
spec:
  containers:
    - name: metadata-service
      image: necromancerthedark/metadata_container:v1.0
      ports:
        - containerPort: 8080
